# Site settings
title: Michael Yoshitaka ERLEWINE (mitcho)
email: mitcho@mitcho.com
description: > # this means to ignore newlines until "baseurl:"
  I am an Assistant Professor in linguistics at the National University of Singapore. I study the structure of sentences (syntax) and how these structures map to meaning (semantics). Much of my work is based on fieldwork on understudied and endangered languages.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mitcho.com" # the base hostname & protocol for your site

# Build settings
markdown:    kramdown
highlighter: pygments
exclude:     ["_hidden"]
timezone:    America/New_York
gems:
  - jekyll-redirect-from
  - jemoji

disqusid: "http://mitcho.com"

# Permalinks
permalink: /blog/:title/

# Markdown
kramdown:
  input: GFM # github-flavored markdown

# SASS
sass:
    style: :compressed
